#!/bin/bash

#Note : one need to replace the line " echo "delete command" " with the hdfs dfs -rmr <hdfs_path>
#######################################################################################
##Script Name   : delete_dir.sh
##Description   : This script basically works as a "rm -r" command.But before delete the directory
##                it will check for the directory inside the directory (which is going to be deleted)
##                and it will show the files present inside the directory and after taking the 
##                confirmation from the user the directory will be deleted
##Create Date   :
##Modified Date :
##version       : 1.0
######################################################################################
rm -f delete_dir_temp1
rm -f delete_dir_temp2

echo "Please enter the Absolute Path of directory which you want to delete : "
read directory
echo "Enter the expected number of files to be deleted $directory : "
read Number


# input_validation validates both the entered inputs from user
input_validation(){
	#validate the directory
	hdfs dfs -ls -R $1 >> delete_dir_temp2
		if [ "$?" -ne 0 ];
			then
			echo "--------------------Directory not found-------------------"
			exit 1
		fi
	
	#validate the number
	[[ "$2" != ?(+|-)+([0-9]) ]] && echo "$2 is not numeric, Please enter a valid number" && exit 1
}

input_validation $directory $Number

# print_details prints the details of the directory ex. how many items,files and directories present
cat delete_dir_temp2 |cut -c 1 >> delete_dir_temp1
var_dir=$(cat delete_dir_temp1 |grep d |wc -l)
var_file=$(cat delete_dir_temp1 |grep - |wc -l)
var_total=$(cat delete_dir_temp1|wc -l)
echo "----------------------------------------------------------"
echo "There are total : $var_total - items in $directory "
echo "  out of which  : $var_dir - directories "
echo "                : $var_file -  files"
echo "----------------------------------------------------------"


# fn (view_files) lists all the filenames present in the directory
view_files(){
	echo "Following are the $1 Files "
	echo "----------------------------------------------------------"
	cat delete_dir_temp2 |awk -F"/" '{print $NF}'
	echo "----------------------------------------------------------"
	echo ""
}

validate_check(){
	# checking whether the directory is empty or not 
	if [ "$1" -eq 0 ] && [ "$2" -eq 0 ];
		then
		echo "This is an empty directory"
		delete_dir
	fi
	# checking if any directories inside the directory
	if [ $1 -ne 0 ];
		then
		echo ""
		echo "There are $1 directories inside $directory";
		echo "---------------Can not delete the directory---------------"
		exit 1
	fi
	# compare the expacted number of files with the actual number of files
	if [ $3 -lt $2 ];
		then
		echo "##############################################################"
        echo "   There are more files then your expected number of files"
		echo "##############################################################"
		view_files $2
		#delete_dir
		exit 1
	elif [ $3 -gt $2 ];
		then
		echo "##############################################################"
        echo "   There are less files then your expected number of files"
		echo "##############################################################"
		view_files $2
		delete_dir
		exit 1
	fi
}


#delete_dir will delete the directory after getting the confirmation from user
delete_dir(){
	echo "Are you sure you want to delete this files ? (y/n) : "
	read choice
	if [ "$choice" = "y" ];
		then
		hdfs dfs -rm -r $directory
		echo "Deleting the Files"
		exit 1
	else
		echo "---------------Can not delete the directory---------------";
		exit 1
	fi
}

validate_check $var_dir $var_file $Number
view_files $var_file
delete_dir $Number
